name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, windows-11-arm]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6
    - name: Cache cargo dependencies
      uses: Swatinem/rust-cache@v2
    
    - name: Build with timings
      run: cargo build --verbose --release --timings
    - name: Run tests
      run: cargo test --verbose --release
    - name: Rename timing report for distinct OS
      shell: bash
      run: |
        cp target/cargo-timings/cargo-timing.html target/cargo-timings/cargo-timing-${{ matrix.os }}.html
    - name: Get binary name
      id: bin
      shell: bash
      run: |
        BIN_NAME=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].targets[] | select(.kind[] | contains("bin")) | .name' | head -1)
        echo "name=${BIN_NAME}" >> $GITHUB_OUTPUT
    - name: Upload build timings report
      uses: actions/upload-artifact@v7
      with:
        name: build-timings-${{ matrix.os }}
        path: target/cargo-timings/cargo-timing-${{ matrix.os }}.html
        if-no-files-found: warn
        archive: false
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ steps.bin.outputs.name }}-${{ matrix.os }}
        path: target/release/${{ steps.bin.outputs.name }}${{ contains(matrix.os, 'windows') && '.exe' || '' }}
        if-no-files-found: error
